// <auto-generated />
namespace Snippets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MadeLabelFieldFromVisibilityRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadeLabelFieldFromVisibilityRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201311081115567_MadeLabelFieldFromVisibilityRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
