// <auto-generated />
namespace Snippets.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateManyToManyRelationBetweenTagsAndSnippets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateManyToManyRelationBetweenTagsAndSnippets));
        
        string IMigrationMetadata.Id
        {
            get { return "201310241014337_CreateManyToManyRelationBetweenTagsAndSnippets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
